### ISSUE TITLE
File search causes app crash

### ISSUE THREAD

**Issue by vinaygopinath** [qwersyk/Newelle#35] opened 2023-07-31 08:35 UTC
## Prompt
"List out all the PDFs in the Downloads folder"

## Expected behaviour
A list of PDF files from the Downloads folder

## Actual behaviour
App crash.

Not sure if this is helpful, but I see the following in the terminal as the app crashes
```
(newelle:2): Gtk-CRITICAL **: 02:32:29.828: gtk_text_attributes_ref: assertion 'values != NULL' failed
**
Gtk:ERROR:../gtk/gtktextlayout.c:1261:set_para_values: code should not be reached
Bail out! Gtk:ERROR:../gtk/gtktextlayout.c:1261:set_para_values: code should not be reached
```

**Comment by FrancescoCaracciolo** [comment] 2024-08-01 21:22
Duplicate of #7

**Closed by FrancescoCaracciolo** 2024-08-01 21:22 UTC
